version: "3"
services:
  icatagent:
    environment:
      ADMIN_PORT: 5000
      AGENT_PORT: 10000
      INDY_SEED: 00000000000000000000000000000000
      GENESIS_TRANSACTIONS: '{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node1","blskey":"4N8aUNHSgjQVgkpm8nhNEfDf6txHznoYREg9kirmJrkivgL4oSEimFF6nsQ6M41QvhM2Z33nves5vfSn9n1UwNFJBYtWVnHYMATn76vLuL3zU88KyeAYcHfsih3He6UHcXDxcaecHVz6jhCYz1P2UZn2bDVruL5wXpehgBfBaLKm3Ba","blskey_pop":"RahHYiCvoNCtPTrVtP7nMC5eTYrsUA8WjXbdhNc8debh1agE9bGiJxWBXYNFbnJXoXhWFMvyqhqhRoq737YQemH5ik9oL7R4NTTCz2LEZhkgLJzB3QRQqJyBNyv7acbdHrAT8nQ9UkLbaVL9NBpnWXBTw4LEMePaSHEw66RzPNdAX1","client_ip":"192.168.65.3","client_port":9702,"node_ip":"192.168.65.3","node_port":9701,"services":["VALIDATOR"]},"dest":"Gw6pDLhcBcoQesN72qfotTgFa7cbuqZpkX3Xo6pLhPhv"},"metadata":{"from":"Th7MpTaRZVRYnPiabds81Y"},"type":"0"},"txnMetadata":{"seqNo":1,"txnId":"fea82e10e894419fe2bea7d96296a6d46f50f93f9eeda954ec461b2ed2950b62"},"ver":"1"}'
      SITE_URL: https://9ff514df.ngrok.io
      WEBHOOK_URL: http://django:8000/webhooks
      DATABASE_URL: postgres
    build:
      context: ..
      dockerfile: docker/indy-catalyst-agent/Dockerfile
    ports:
      - "5000:5000"
      - "10000:10000"
    volumes:
      - icatagent:/home/indy/.indy_client/wallet
    command: bash -c "icatagent -it http 0.0.0.0 $${AGENT_PORT} -ot http --admin 0.0.0.0 $${ADMIN_PORT} -e https://9ff514df.ngrok.io --wallet-type indy --seed 00000000000000000000000000000000 --genesis-transactions '$${GENESIS_TRANSACTIONS}' --accept-invites --accept-requests"

  django:
    depends_on:
      - postgres
    environment:
      PORT: 8000
      SITE_URL: http://localhost:8000
      DEBUG: "true"
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      DB_HOST: postgres
      EMAIL_HOST: maildev
      EMAIL_PORT: 25
      EMAIL_USE_SSL: "false"
    build:
      context: ..
      dockerfile: docker/email-verification-service/Dockerfile
    working_dir: /app
    ports:
      - 8000:8000
    command: bash -c "./manage.py makemigrations &&./manage.py migrate && ./manage.py runserver 0.0.0.0:$${PORT}"
    volumes:
      - ../src:/app

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      # POSTGRES_DB: app
      # POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  maildev:
    image: djfarrelly/maildev
    ports:
      - "8050:80"

volumes:
  django:
  icatagent:
